#!/usr/bin/env python3

import subprocess
import csv
import os
import sys
from datetime import datetime

# binary is built at project root, one level up from tests/
BINARY = "../vehicle_ecu"
CSV    = os.path.join(os.path.dirname(__file__), "test_vectors.csv")
REPORT_FILE = os.path.join(os.path.dirname(__file__), "test_report.html")

ALERTS = ["DEPLOY AIRBAG", "EMERGENCY BRAKE", "LOW FUEL WARNING", "ALARM ON"]

html_template = """
<!DOCTYPE html>
<html>
<head>
<title>HIL Automated Test Report</title>
<style>
    body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #1e1e2e; color: #cdd6f4; margin: 2rem; }}
    h1 {{ color: #89b4fa; border-bottom: 2px solid #45475a; padding-bottom: 0.5rem; }}
    .summary {{ background-color: #313244; padding: 1rem; border-radius: 8px; margin-bottom: 2rem; display: flex; gap: 2rem; }}
    .summary div {{ flex: 1; }}
    .summary strong {{ color: #bac2de; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; background-color: #181825; box-shadow: 0 4px 6px rgba(0,0,0,0.3); border-radius: 8px; overflow: hidden; }}
    th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #313244; }}
    th {{ background-color: #45475a; color: #f38ba8; font-weight: bold; text-transform: uppercase; letter-spacing: 0.05em; font-size: 0.9em; }}
    tr:last-child td {{ border-bottom: none; }}
    tr:hover {{ background-color: #313244; transition: 0.2s; }}
    .pass {{ color: #a6e3a1; font-weight: bold; }}
    .fail {{ color: #f38ba8; font-weight: bold; }}
    .footer {{ margin-top: 2rem; font-size: 0.8em; color: #6c7086; text-align: center; }}
</style>
</head>
<body>
    <h1>Vehicle ECU - Automated HIL Test Report</h1>
    <div class="summary">
        <div><p><strong>Timestamp:</strong> {timestamp}</p></div>
        <div><p><strong>Total Tests:</strong> {total}</p></div>
        <div><p><strong>Passed:</strong> <span class="pass">{passed}</span></p></div>
        <div><p><strong>Failed:</strong> <span class="fail">{failed}</span></p></div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Test #</th>
                <th>Impact</th>
                <th>Distance</th>
                <th>Fuel</th>
                <th>Tamper</th>
                <th>Expected Output</th>
                <th>Actual Output</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {table_rows}
        </tbody>
    </table>
    <div class="footer">
        Generated by ECU Automated Testing Suite
    </div>
</body>
</html>
"""

def run_test(row, test_num):
    cmd = [BINARY, row["impact"], row["distance"], row["fuel"], row["tamper"]]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
    output = res.stdout.upper()

    expected = row["expected"].strip().upper()
    actual = "ALL SYSTEMS NORMAL"

    if expected == "ALL SYSTEMS NORMAL":
        passed = not any(a in output for a in ALERTS)
        for a in ALERTS:
            if a in output:
                actual = a
                break
    else:
        passed = expected in output
        if expected in output:
            actual = expected
        else:
            for a in ALERTS:
                if a in output:
                    actual = a
                    break
            if actual == "ALL SYSTEMS NORMAL" and "ALL SYSTEMS NORMAL" not in output:
                 actual = "UNKNOWN / TIMEOUT"

    if passed:
        print(f"  Test #{test_num:02d}  PASS  ({expected})")
        status_html = "<td class='pass'>PASS</td>"
    else:
        print(f"  Test #{test_num:02d}  FAIL")
        status_html = "<td class='fail'>FAIL</td>"

    # HTML row formatting
    row_html = f"""<tr>
        <td>{test_num:02d}</td>
        <td>{row['impact']}</td>
        <td>{row['distance']} cm</td>
        <td>{row['fuel']}%</td>
        <td>{row['tamper']}</td>
        <td>{expected}</td>
        <td>{actual}</td>
        {status_html}
    </tr>"""

    return passed, row_html


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    binary_abs = os.path.join(script_dir, "..", "vehicle_ecu")

    if not os.path.exists(binary_abs):
        print("Binary not found. Run 'make' from the project root first.")
        sys.exit(1)

    global BINARY
    BINARY = binary_abs

    passed = 0
    failed = 0
    table_rows = []

    print()
    with open(CSV, "r") as f:
        for i, row in enumerate(csv.DictReader(f), 1):
            is_pass, row_html = run_test(row, i)
            table_rows.append(row_html)
            if is_pass:
                passed += 1
            else:
                failed += 1

    total = passed + failed
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    final_html = html_template.format(
        timestamp=timestamp,
        total=total,
        passed=passed,
        failed=failed,
        table_rows="\\n".join(table_rows)
    )

    # Clean up escaping from format mapping
    final_html = final_html.replace("\\n", "\n")

    with open(REPORT_FILE, "w") as f:
        f.write(final_html)

    print()
    print("----------------------------")
    print(f"  Tests Run : {total}")
    print(f"  Passed    : {passed}")
    print(f"  Failed    : {failed}")
    print("----------------------------")
    print(f"  -> Detailed HTML report written to: {REPORT_FILE}")
    print()

    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
